const os = require('os')

// console.log(os.EOL)
// console.log(os.arch())
// console.log(JSON.stringify(os.cpus(), null, 4))
// console.log(os.freemem()/1024/1024)
// console.log(os.homedir())
// console.log(os.hostname())
// console.log(JSON.stringify(os.networkInterfaces(), null, 4))
// console.log(os.platform())
// console.log(os.release())
// console.log(os.tmpdir())
// console.log(os.totalmem()/1024/1024)
// console.log(os.type()
// console.log(os.uptime())
// console.log(os.userInfo())
// console.log(os.constants.SIGINT)